package com.example.datasourcedemo;

import org.mybatis.spring.annotation.MapperScan;
import org.springframework.boot.SpringApplication;
// 移除未使用的导入语句 org.springframework.boot.autoconfigure.EnableAutoConfiguration
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.scheduling.annotation.EnableAsync;

// Generated by https://start.springboot.io
// 优质的 spring/boot/data/security/cloud 框架中文文档尽在 => https://springdoc.cn
@SpringBootApplication
@MapperScan("com.example.datasourcedemo.mapper")
@EnableAsync
public class DatasourceDemo1Application {

    public static void main(String[] args) {
        SpringApplication.run(DatasourceDemo1Application.class, args);
        System.out.println("启动成功");
    }

}
